Public/Add-NotebookJob.ps1
Tests/Add-NotebookJob.tests.ps1

I created Powershell script that uses Databricks API 2.0 to create a Notebook Job based on provided parameters.

Script for adding notebook job to Databricks

---

Public/Restart-DatabricksCluster.ps1
azure.databricks.cicd.Tools.psd1

extended from the Start-DatabricksCluster.ps1 code

added Restart-DatabricksCluster command

---

Public/Remove-DatabricksNotebook.ps1
Tests/Remove-DatabricksNotebook.tests.ps1
azure.databricks.cicd.Tools.psd1

Option to delete item from workspace (Folder or Notebook)

added Delete option #55

---

Public/Add-DatabricksNotebookJob.ps1
Public/Add-DatabricksPythonJob.ps1
Tests/Add-DatabricksNotebookJob.tests.ps1

Support run immediate on notebook jobs

#63 Support run immediate on notebook jobs

---

Private/SCIMFunctions.ps1
Public/Add-DatabricksUser.ps1
Public/Get-DatabricksPermissionLevels.ps1
Public/Get-DatabricksServicePrincipals.ps1
Public/Set-DatabricksPermissions.ps1
Tests/Add-DatabricksJarJob.tests.ps1
Tests/Add-DatabricksLibrary.tests.ps1
Tests/Add-DatabricksNotebookJob.tests.ps1
Tests/Add-DatabricksPythonJob.tests.ps1
Tests/Get-DatabricksJobRunList.tests.ps1
Tests/Get-DatabricksLibraries.tests.ps1
Tests/Get-DatabricksPermissionsLevel.tests.ps1
Tests/Get-DatabricksRun.tests.ps1
Tests/Get-DatabricksServicePrincipals.tests.ps1
Tests/Remove-DatabricksLibrary.tests.ps1
Tests/SCIMFunctions.tests.ps1
Tests/Set-DatabricksPermission.tests.ps1
Tests/config.sample.json
azure.databricks.cicd.tools.psd1

SCIM & Permissions

---

Private/ConnectFunctions.ps1
Public/Connect-Databricks.ps1
Public/Get-DatabricksServicePrincipals.ps1
Public/Invoke-DatabricksAPI.ps1
README.md
Tests/Add-DatabricksSecretScope.tests.ps1
Tests/Connect-Databricks.tests.ps1
Tests/ConnectFunctions.tests.ps1
Tests/Invoke-DatabricksAPI.tests.ps1
Tests/_InvokeTests.ps1
Tests/config.sample.json
azure.databricks.cicd.tools.psd1

Rename ClientId to ApplicationId

---

.gitignore
Public/Add-DatabricksSecretScope.ps1

Might help detect -AllUsersAccess

try to detect option on std spaces (can't repo) #58

---

Public/Remove-DatabricksGroup.ps1

It seems like the description was the same as in Remove-DatabricksJob

Changed the description of the parameter GroupName

---

Private/Set-LocalNotebook.ps1

Fix for issue #90 
Uses ```Invoke-WebRequest -Outfile``` to save to temp file then get-content specifying utf-8 to remove weird encoding.

Weird encoding

---

Public/Add-DatabricksNotebookJob.ps1

Inside the function there was a lack on setting alerts to set a notebookjob.
https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/jobs#--jobemailnotifications
I've added the 4 parameters mentioned in the docs of the api. to the function.

Added Alert settings on notebook jobs

---

Public/Import-DatabricksFolder.ps1
Public/Remove-DatabricksNotebook.ps1
Tests/Import-DatabricksFolder.tests.ps1

Resolve #98  #NextDeploy
Slow - but retains permissions.

Delete existing files one at time when using -Clean

---

Public/Set-DatabricksSecret.ps1
Tests/Set-DatabricksSecret.tests.ps1

escape secrets with \ 

---

README.md
Tests/_InvokeTests.ps1

Click on badges in Readme to see project

Move to Public Azure DevOps Project

---

Tests/Samples/DummyJobs/dummyJob.json

remove my email from jobs so I don't get alerts from Azure that job has been created/started/deleted etc...

change test job

---

Public/Import-DatabricksFolder.ps1
Tests/Export-DatabricksFolder.tests.ps1
Tests/Import-DatabricksFolder.tests.ps1
Tests/Samples/DummyNotebooks/CleanTest/Folder1/CleanTestFile1.py
Tests/Samples/DummyNotebooks/CleanTest/Folder2/CleanTestFile2.py

Fixes #127 
A couple of the test broke - I think because they may not run in order. Just cleaned up slightly

Fixing broken clean switch on Import-DatabricksFolder

---

Private/Get-Notebooks.ps1
Public/Import-DatabricksFolder.ps1

I (and others) have been getting odd issues where lines are added to notebooks when being pushed. Have been able to switch out ```readallbytes``` for ```get-content -asbytestream``` and issue has gone. However it is not in PowerShell 5 so needed to add a little check.
https://github.com/DataThirstLtd/azure.databricks.cicd.tools/compare/master...RichieBzzzt:blanklines?expand=1#diff-b359969e450ddf2a3bac47abc8e5b74aR89
Also removed the blank line that appears for each download of the notebooks, finally!

Fix blank line issues on Ubuntu/PowerShell 7

---

Private/Get-Notebooks.ps1

..to remove line ending issues. See #138

set content if file already exists

---

Public/Get-DatabricksSecretByScope.ps1
Public/Set-DatabricksSecret.ps1
Tests/Set-DatabricksSecret.tests.ps1

Been having issues with passing json content as secrets; using hashtable then convertto-json seems to have fixed it. Have added tests for other secret types that may be stored.

Secretformatting

---

Public/Add-DatabricksDBFSFile.ps1
Tests/Add-DatabricksDBFSFile.tests.ps1

Wrong attribute was being passed to Write-Verbose
Also fixed another incorrect assertion in the same `Describe`

Correct verbose output of Add-DatabricksDBFSFile

---

Private/GetNewCluster.ps1

This fixes the issues #159 and #160 
@simondmorias is this enough with this?

Fix for being able to create Single Node clusters and pass empty InitScripts in New-DatabricksCluster

---

Public/Get-DatabricksSCIMURL.ps1
azure.databricks.cicd.tools.psd1

Get-DatabricksSCIMURL

---

Public/Connect-Databricks.ps1
README.md

Allow the logging is use your current Az Context (Get-AzContext).
Allows logging in as a user
Note requires Az Module 5.1 or higher.

Connect use Az PowerShell Context

---

Public/Add-DatabricksNotebookJob.ps1
Tests/Add-DatabricksNotebookJob.tests.ps1

- Bumped up version of Jobs API to 2.1 
- Altered from "reset" to "update" as per documentation guide.
- Added access_control_list as an option on ```Add-DatabricksNotebookJob```

jobsnotebook api to 2.1;add acl param; using update instead of reset
